### ISSUE TITLE
Proposal: silverstripe-console

### ISSUE THREAD

**Issue by robbieaverill** [silverleague/silverleague.github.io#1]
# silverleague/silverstripe-console

**Repository:** https://github.com/silverleague/silverstripe-console
**Specification:** https://silverleague.github.io/development/silverstripe-console

## Introduction

The SilverLeague Console is a [Symfony console](http://symfony.com/doc/current/components/console.html) application which interfaces directly with a SilverStripe application for a better command line experience.

## Use case

The [SilverStripe framework](https://github.com/silverstripe/silverstripe-framework) ships with a built in CLI management tool - "framework/cli-script.php". It also has a bash wrapper called "sake". This tool essentially lets you run controllers from the command line in much the same way as you would from the browser, while providing added benefits such as not having to worry about web server timeouts, being able to run in a cron task, etc.

This tool is limited. The SilverLeague console aims to replace its use with a more powerful, flexible and featured tool for managing SilverStripe applications.

## Aims over other community modules

There are some existing CLI modules for SilverStripe among the community already. This module is going to be built with the following focusses:

* SilverLeague concepts first
* PHP 5.6+ minimum (in turn, PHPUnit 5.7)
* SilverStripe 4 minimum (?)
* Don't use "sake" or variations of the same, since they mean nothing to unaware developers
* Don't ship as a module that should be installed into a SilverStripe application - should run standalone

This module would not support SilverStripe 3.x at this stage. Users would be recommended to use an established console like ["supersake"](https://github.com/axyr/silverstripe-console) for legacy framework/CMS support.

## Functionality

- [x] Most importantly the console will automatically detect all `BuildTask` instances from the SilverStripe application and expose them as console commands
- [x] Database build, manifest flushing: silverleague/silverstripe-console#9
- [ ] Database management (import, dump, dev-stripping): silverleague/silverstripe-console#5
- [ ] Asset management (import, dump): silverleague/silverstripe-console#6
- [x] Member management (create, change password, change groups)
- [ ] Cache management (clear, inspect, clear individual areas): silverleague/silverstripe-console#4
- [x] Config inspection - search by class name or property name: silverleague/silverstripe-console#3
- [ ] Module creation - initialise a new module, choose classes to extend and choose new DataObjects to create: silverleague/silverstripe-console#8
- [ ] Extensibility - ability to add custom commands to a user directory, or specific folder in a SilverStripe application to be run by the console: silverleague/silverstripe-console#7
- [x] SilverStripe Extensions - list by class name: silverleague/silverstripe-console#1
- [x] Concrete extensions - list by class name: silverleague/silverstripe-console#2
- [ ] Delete DataObjects - ability to remove DataObjects by class name and ID/URL route: silverleague/silverstripe-console#28
- [x] DataObject debug output (dump) - ability to dump a DataObject by class name and ID/URL route with output formatted cleanly: silverleague/silverstripe-console#29
- [x] ~~Discussion: Support both 3.x and 4.x versions without needing a different console version installed~~ Removed

## License

To be released under the MIT license.

**Comment by Firesphere** [comment]
Sorry, I would prefer @axyr his work here. His console module is way more complete and stable and provides a coherent CLI interface.

**Comment by dmc-core** [comment]
Debugging output and the ability to completely delete pages would be a nice touch!

**Comment by robbieaverill** [comment]
Thanks @dmc-core - I've adjusted your suggestions to be for DataObjects generally instead of Pages. Great idea.

**Comment by dmc-core** [comment]
Thinking about the db and assets export/imports could we utilise sspak as a requirement and wrap it in its own namespace?  Could then pass in its expected args etc from the single cmd.  Ie sspak:load [args]

**Comment by robbieaverill** [comment]
@dmc-core I like that. It would remove our database and assets command scope, and we add `sspak` as a command namespace which is literally a wrapper for sspak, which can be included with composer and bootstrapped accordingly

**Comment by sminnee** [comment]
How does this compare to https://github.com/axyr/silverstripe-console?

**Comment by robbieaverill** [comment]
The comparison is very similar.

_I think_ what this proposal is trying to achieve that other consoles (cli-script/sake, [supersake](https://github.com/axyr/silverstripe-console) and [sakemore](https://github.com/superspring/sakemore)), as well as sspak etc, don't already can be loosely summed up as:

* A modern [tech wise] and combined approach - use one tool that covers functionality from all others you may need
* This is not a SilverStripe module, it's a utility (do not install into the web root or the SilverStripe framework) - you install globally with composer, or we potentially compile a phar at some stage - especially since the global Symfony Console requirement conflicts with that of the upgrader tool (if installed globally as well)
* Extensibility - users can define their own commands, or write and publish their own modules that extend it
* The idea's been mooted that this console should support both SS 3 and 4 within the same utility
* Active support - the other modules appear to either be forgotten about, ignored or on a low priority

The general ideas of SilverLeague in terms of high quality code, exhibiting best practices for development/architecture, high test coverage etc apply too, but aren't necessarily unique to this console versus the others.

---

Those are pretty high level, but on a granular level, one thing this module does that supersake doesn't is the ability to see all native SS tasks and run them.

**Comment by sminnee** [comment]
> This is not a SilverStripe module, it's a utility (do not install into the web root or the SilverStripe framework) - you install globally with composer, or we potentially compile a phar at some stage - especially since the global Symfony Console requirement conflicts with that of the upgrader tool (if installed globally as well)

Yeah, it's difficult (but not impossible) to make a single package that combines both use-cases. I would probably note that the approach of other tools such as phpunit has been do go the other way, and notably in SS4 you can't use the globally installed version. We've chosen this approach for a number of reasons:

 * We need different versions of PHPUnit for different projects
 * Developers will automatically get the packages we need by running `composer update`
 * We can use the location of the referenced `vendor/` folder to determine the `BASE_PATH` of the project. This has been used to good effect in letting you run `silverstripe/serve` and phpunit directly from the framework folder, rather than needing to "build a project structure" to develop on the framework. More generally, it helps allow for flexibility in the project structure.

To that effect, in SS4 I was keen to see both silverstripe/serve get a bit more love as a recommended dev tool, and for sake to be replaced with something provided by a separate project-specific dependency, that puts a binary into `vendor/bin`.

**Comment by robbieaverill** [comment]
Yeah - this module _will_ run as a project dependency (as the others do too) and that would mean less magic for adapting multiple major SS versions in one app and instead just installing the appropriate tag for your SS version. I personally prefer tools like this to be separate from the codebase, but can see the benefits of having it bundled in with it too

**Comment by sminnee** [comment]
Presumably you might have extensions to the CLI tool that only apply to a given project. In these cases it would make sense to have the extension loaded into the project rather than globally.

You might set up an architecture where if the global tool detects that the in-project tool is installed, it defers all the commands to it. That could potentially leave the global tool quite lean, and make a cross-major-version tool more feasible without a bunch of if blocks.

**Comment by robbieaverill** [comment]
True. You could also have a global utility that looks for local modules

**Comment by axyr** [comment]
That would over complicate things...

What about commands I want to use on production?

**Comment by robbieaverill** [comment]
I guess if you have production ssh access then you would also have access to install a utility into the path. As I say though, this can currently be installed as a silverstripe dependency as well, it's just that I'd encourage against it :-)

**Comment by robbieaverill** [comment]
For reference, the Magento equilavent (which I'm trying to model this on) [n98-magerun](https://github.com/netz98/n98-magerun) doesn't appear to encourage installation inside a Magento project, nor augment any functionality within the app (like admin interfaces). I'm not sure whether than means you couldn't install it as a composer dependency at all though

**Comment by axyr** [comment]
Checkout Laravel. There are tons of use cases you want have console commands on production. 

I have several website spiders that are solely ran from scheduled commands.

Or scheduled mailers, maintenance scripts etc. Putting a site in 503. 

So if I have 1 site that needs console commands, I need to install a tool global that could otherwise just als easy added as a composer dependency with the correct tag that I require for that project?

**Comment by robbieaverill** [comment]
You completely _can_ install into your project if it suits your use case

**Comment by sminnee** [comment]
It might be helpful to elaborate on what you see as the biggest benefits of installing the tool globally. Is it about easy execution, smaller project size, ability to run commands such as "create project" that don't naturally fit into a single project, or something else?

**Comment by robbieaverill** [comment]
Here's what I see as the pros and cons of both ways:

## Global install

### Pros

* One installation per server/development environment (assuming the utility is cross-version supported)
* No need to include it as a project dependency (faster installs, less clutter)
* Ability to perform project agnostic tasks (for example, what sspak does and what [Martijn's CLI installer](https://github.com/axyr/silverstripe-cli-installer) does)

### Cons

* If installed with composer (as opposed to a bundled application) there is the potential for version conflicts in the global composer dependencies which could prevent you from installing it (valid example - this module and silverstripe-upgrader require different major versions of Symfony console)
* If installed with composer then the composer's bin folder needs to be available in the user's PATH. This adds an extra installation step if it's not configured this way already from other installs.

## In-project

### Pros

* Lock each project to a specific version of the utility
* Don't worry about it being available - wherever your project goes, it will likely follow
* No need to remember to install it in a new environment as it will come with the project's `composer install`

### Cons

* Same as the global install - potential for local composer package conflicts (in fact, it's much more likely in this instance)
* Many instances of the module on one machine if there are many projects (however, again, it's locked to the project version)

---

Both install options would be able to support local extensions to the application (within the _project_, or user's home folder in the environment, or both).

I think that the "preferred installation option" would probably guide a decision like "should we support multiple SilverStripe framework versions in a single app, or have different versions for each" - since you don't need the added complexity of the former if you're deploying natively into a project, and you probably do if you deploy globally.

Otherwise, I think it's largely going to come down to the preference of the developer using it - the tool supports both options already. It'd be good to choose a little more definitely which way to go, which will naturally guide the decision mentioned above re: version support.

I'm already pretty indifferent - if people want to install it into a project, that's cool, if they want to install it globally, that's fine too.

**Comment by Firesphere** [comment]
Can you get a comparison between @axyr his work and yours? This still feels to me as a "I did this, so take mine" over "This is the best solution".

**Comment by robbieaverill** [comment]
>"I did this, so take mine" over "This is the best solution".

It's not like that - there wasn't a suitable module for what I wanted to do (outlined previously), and the existing consoles (there are many, not just one) aren't on offer here.

I'm mostly dubious of reinventing wheels, which is why I've tried to propose a substantial set of improvements over what any of the others offer.

**Comment by robbieaverill** [comment]
1.0.0 tagged, not all of the initial features made it in but it's got some useful ones.
