### ISSUE TITLE
Proposal: silverstripe-logviewer

### ISSUE THREAD

**Issue by robbieaverill** [silverleague/silverleague.github.io#5]
# silverleague/silverstripe-logviewer

**Specification:** https://silverleague.github.io/complete/silverstripe-logviewer

## Introduction

As a developer you may not be as aware of SilverStripe logging as you may want to be.

This module intends to *add* a Monolog logger which will log to a database table that can be rendered to an area of the CMS admin for easy viewing.

## Why?

Because logs often go unnoticed, and since the 4.x framework has Monolog bundled with it, we can easily add a new `LoggerInterface` to push logs to the database. From here, they can easily be displayed in the admin as a GridField or similar.

## Details

A new CMS section which displays a GridFields listing all log entries stored.

Columns could be: log content, date/time, log level.

~Provide the filter to certain log levels, and allow the GridField to be filterable so I could search for "Deprecated" for example, or to filter by a date range.~ Handled by GridField.

We would implement a `BuildTask` and/or a `CronTask` which would clear the logs that are older than *x* days (7? 14? 30?). A button in the CMS admin interface would also allow you to clear old logs.

~Export to CSV functionality would be useful as well.~ Handled by GridField.

## Functionality

- [x] Add new CMS interface to the admin area
- [x] Create `DataObject` representing a log entry
- [x] Add and configure new monolog `LoggerInterface` to push the log into a new `LogEntry` (for example)
- [x] Implement filterable/searchable/orderable GridField in the CMS admin
- [x] Add `BuildTask`/`CronTask`/both to remove old log entries automatically: silverleague/silverstripe-logviewer#3
- [x] Add button to CMS to remove all log entries manually: silverleague/silverstripe-logviewer#4
- [x] Configure the minimum log level to handle: silverleague/silverstripe-logviewer#2

**Comment by anselmdk** [comment]
There is a simple log viewer here (which I recently upgraded to SS4): https://github.com/i-lateral/silverstripe-logviewer/pull/2
Just for inspiration.

**Comment by gregsmirnov** [comment]
Heh, no SS3 upgrade :)

**Comment by robbieaverill** [comment]
Thanks, I'll take a look. @anselmdk do you think it's worth us doing this module as a "better" version of that?

**Comment by robbieaverill** [comment]
Just had a look. I think there's a good case to continue with this proposal.

**Comment by anselmdk** [comment]
So i-lateral's module basically loops through files in the logs directory. It's pretty basic, but works. I do like the idea though of using monolog to write to the database, which allows for more flexibility. I'm just not sure you'd always want to log everything to the database. Would it make sense to have 2 options?
Here's a screenshot of how the module looks like in SS4:

<img width="996" alt="screenshot 2017-01-05 18 27 44" src="https://cloud.githubusercontent.com/assets/1316533/21690765/fb30ce74-d375-11e6-86ff-dae333b0988d.png">

**Comment by robbieaverill** [comment]
Sounds good. Yeah, using monolog gives plenty of storage options. I think the DB will be the most native option for SS though. Writes are pretty lightweight so I shouldn't imagine too much of a performance impact.

**Comment by anselmdk** [comment]
Maybe falling back to the file system when the db is not available/experiencing issues?

**Comment by robbieaverill** [comment]
To be clear I was suggesting a second handler for this, not a replacement of whatever is already there

**Comment by anselmdk** [comment]
Ok, so you're suggesting that log files would still be written?

**Comment by robbieaverill** [comment]
Yes absolutely. We can add another handler specifically for this case

**Comment by robbieaverill** [comment]
I've added a quick proof of concept for this here: https://github.com/robbieaverill/silverstripe-logviewer

I'm happy to be the "maintainer". If we've got a co-maintainer and "advocate" then let's get moving with it!

**Comment by Firesphere** [comment]
I think it would be a good module to have. Although there needs to be a level of finetuning before writing to the database.

A good option would also be to have a level of logging (err/warn/info) to filter on.

**Comment by robbieaverill** [comment]
Sure, good idea @firesphere. What do you suggest as the default levels to keep? Debug up? Warning up? Error up? Debug to warning maybe, but not errors or higher?

Maybe we could be smarter about this and read from the default logger instead of writing to and reading from a new logger.

---

Monolog provides a minimum level to start logging at (in PSR-3 terms). I've added WARNING as the default minimum, but it can be configured in YAML if someone wanted everything, or less.

**Comment by robbieaverill** [comment]
:boom: Feature complete! [v0.1.0 released](https://github.com/silverleague/silverstripe-logviewer/releases/tag/0.1.0).

**Comment by robbieaverill** [comment]
💥  Documentation added, [v1.0.0-alpha1 released](https://github.com/silverleague/silverstripe-logviewer/releases/tag/1.0.0-alpha1).
